# don't build tags, it's redundant
#this tells travis, outside of applitools what to run
if: tag IS blank
language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
    - libgconf-2-4
script: #first line is the most important line, telling travis to cexport the commit SHA to be the batch id
  - export APPLITOOLS_BATCH_ID=`echo ${TRAVIS_PULL_REQUEST_SHA:=$TRAVIS_COMMIT}`
  # echo the batch ID then need to run the test
  - echo $APPLITOOLS_BATCH_ID
  - npm install
  - npx eyes-setup
  #  need the full path
  - npx cypress run --spec "cypress/integration/examples/cicd.spec.js"